package org.monarchinitiative.fhir2hpo.hpo;

/**
 * This class represents an inferred conversion result generated by analyzing the relationships
 * between HPO Terms found in the first-level analysis. The inputs may vary, so for now only a
 * description of the rule is provided.
 * 
 * @author yateam
 *
 */
public class InferredConversionResult {
	
	HpoTermWithNegation hpoTerm;
	String description;
	
	public InferredConversionResult(HpoTermWithNegation hpoTerm, String description) {
		this.hpoTerm = hpoTerm;
	}
	
	public HpoTermWithNegation getHpoTerm() {
		return hpoTerm;
	}

}
